# Generated by Django 5.0.7 on 2024-07-12 22:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('info_adicional_dir', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo_hotel', models.EmailField(max_length=100)),
                ('cant_habitaciones', models.IntegerField()),
                ('desc_hotel', models.TextField(blank=True, null=True)),
                ('imagen_hotel', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id_serv_adicional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_serv_adicional', models.CharField(max_length=50)),
                ('desc_serv_adicional', models.TextField(blank=True, null=True)),
                ('precio_serv_adicional', models.IntegerField()),
                ('imagen_serv_adicional', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_habitacion', models.CharField(max_length=20)),
                ('cant_camas', models.IntegerField()),
                ('bano_privado', models.BooleanField()),
                ('precio_noche', models.IntegerField()),
                ('desc_tipo_habitacion', models.TextField(blank=True, null=True)),
                ('imagen_tipo_habitacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('rol', models.CharField(choices=[('M', 'Marketing'), ('G', 'Gerencia')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPorHotel',
            fields=[
                ('id_servicio_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaweb.hotel')),
                ('serv_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaweb.servicioadicional')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('codigo_promocion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_promocion', models.CharField(max_length=100)),
                ('desc_promocion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porc_descuento', models.IntegerField()),
                ('imagen_promocion', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('estado_promocion', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada'), ('F', 'Finalizada')], default='P', max_length=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaweb.hotel')),
                ('publicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones_publicadas', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaweb.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.IntegerField()),
                ('estado_habitacion', models.BooleanField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaweb.hotel')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaweb.tipohabitacion')),
            ],
        ),
    ]
