# Generated by Django 5.0.7 on 2024-07-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('M', 'Marketing'), ('G', 'Gerencia')], max_length=1, null=True),
        ),
    ]
