# Generated by Django 5.0.7 on 2024-07-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('hotel', 'numero_habitacion')},
        ),
    ]
