# Generated by Django 5.0.7 on 2024-07-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0003_alter_habitacion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicioporhotel',
            unique_together={('hotel', 'serv_adicional')},
        ),
    ]
