# Generated by Django 5.0.7 on 2024-07-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0004_alter_servicioporhotel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='fecha_creacion',
        ),
    ]
